# Generated by Django 5.0.1 on 2024-09-11 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('company_type', models.CharField(choices=[('factory', 'Завод'), ('retail_network', 'Розничная сеть'), ('individual_business', 'Индивидуальное предприниматель')], max_length=20, verbose_name='Тип компании')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('country', models.CharField(max_length=150, verbose_name='страна')),
                ('city', models.CharField(max_length=150, verbose_name='город')),
                ('street', models.CharField(max_length=150, verbose_name='улица')),
                ('house_number', models.CharField(max_length=10, verbose_name='номер дома')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Задолженность перед поставщиком')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='company.company', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='company.company', verbose_name='Компания-владелец')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
